### PR TITLE
add first email

### PR DESCRIPTION
**Pull request by ashleygwilliams**
blocked by @cowperthwait :)
need the unsubscribe link

### CODE REVIEW

**Comment by cowperthwait** [comment]
@ashleygwilliams: 

<a title="Unsubscribe" data-targettype="sysaction" href="http://s2030806319.t.en25.com/e/cu?s=<eloqua type='emailfield' syntax='siteid'/>&elqc=<eloqua type='emailfield' syntax='campaignid'/>&elq=<eloqua type='emailfield' syntax='recipientid'/>&elqTrackId=9B166519B49650F7729C69FEB309EFD9">Here is my link</a>

**Comment by cowperthwait** [comment]
link shared w/ @ashleygwilliams [in Slack](https://npm-inc.slack.com/archives/npm-camp/p1453998503000070)

**Comment by ashleygwilliams** [comment]
can u give this a r @cowperthwait ? no rush

**Comment by cowperthwait** [comment]
test message sent 2016-01-28 ~9:42a;

@ashleygwilliams: please review as delivered and ensure you’re happy with the formatting and where the links go.

**Comment by ashleygwilliams** [comment]
not gonna do this, closing

**Pull request closed without merging**
